### ISSUE TITLE
complier error!!!   need help.

### ISSUE THREAD

**Issue by TestVan** [gclkaze/MonoInLinux#1]
[root@localhost TestCall]# ./a.out 
process()!!

Unhandled Exception:
System.DllNotFoundException: System.Native
[ERROR] FATAL UNHANDLED EXCEPTION: System.DllNotFoundException: System.Native
![20190807153641](https://user-images.githubusercontent.com/50074809/62603768-3b3a8780-b929-11e9-9d9b-627f3c88d744.png)

**Comment by gclkaze** [comment]
Hi, first you need to make a new project on Windows, "TestDLL" then copy paste the Program.cs file from the Windows folder. Compile it and this should create the testdll dll. Then compile the linux folder on a linux system that has Mono enabled/installed. Place the testdll file in the same folder in the Linux system, compile the C++ code and run it. 
Please let me know if it went well.
But first, you will need the testdll file.
Cheers!

**Comment by TestVan** [comment]
> Hi, first you need to make a new project on Windows, "TestDLL" then copy paste the Program.cs file from the Windows folder. Compile it and this should create the testdll dll. Then compile the linux folder on a linux system that has Mono enabled/installed. Place the testdll file in the same folder in the Linux system, compile the C++ code and run it.
> Please let me know if it went well.
> But first, you will need the testdll file.
> Cheers!

Environment :  centos 7 64 bit， mono version :6.0.

Yes , I compile the dll,  it works  fine on windows.   in centos ,  also  System.Native  dllmap  link was added  in /etc/mono/config,   but  it till not works. Ccould you tell me the  envirmoment you use ? Any help would be greatly appreciated.
![20190813142048](https://user-images.githubusercontent.com/50074809/62919725-2309b300-bdd6-11e9-9ee1-05ada406ef60.png)
![20190813142131](https://user-images.githubusercontent.com/50074809/62919744-2d2bb180-bdd6-11e9-8a9d-f7984a942053.png)

**Comment by gclkaze** [comment]
This is my mono/system setup:
Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen


Is the call to mono_jit_init failing? If yes,
try the following:
1. either change the "test.dll" in C++ Linux/Kazelib.cpp to "./test.dll". 
2. either call mono_set_dirs before mono_jit_init in order to specify your assemblies folder (the project's folder).   (http://docs.go-mono.com/index.aspx?link=xhtml%3Adeploy%2Fmono-api-embedding.html)
Cheers!

**Comment by TestVan** [comment]
no, mono_jit_init is not failed,   the MonoMain is not a empty pointer.  Still can't find system.Native ,I think  it may  link error.
![20190814144941](https://user-images.githubusercontent.com/50074809/63000074-d3dd8400-bea2-11e9-877a-d6863276eadf.png)

**Comment by TestVan** [comment]
fix on mono jit version 5.18
